### ISSUE TITLE
travis scripts that reside on bintray.com unversioned?

### ISSUE THREAD

**Issue by mfro0** [freemint/travis-scripts#5]
I'm just trying to understand all the script magic that does automated builds.

Aren't the build scripts that the travis build environment pulls from bintray supposed to be here (under git control) as well?

**Comment by mikrosk** [comment]
You are correct, it's quite a magic. The main reason for that is that I (and @atic-atac) didn't want to have the scripts (and additional files for aranym for instance) in the repository, minimising the amount of commits related to them.

You are in the right repository, though. :) The confusion is caused mostly by the fact there are two ways how Travis is deployed:
1. the old method where some scripts are still in the project's repository and only common part is downloaded from here (`mintlib`, `gemlib`, `cflib`, `qed`, ...) ... usually 'some' means related to building so as soon a bug is discovered you have to fix & commit it in the respective repository.
1. the new method which is used by `freemint` which publishes things on bintray.com and has only a bootstrap script inside its repository. So if a bug is found, in 99% of cases you fix it in this repository (travis-scripts) and not the one for given project (freemint).

For `1.`, the master branch of this repository is used. You can see it here for instance: https://github.com/freemint/mintlib/blob/master/.travis.yml ... the interesting parts are `build.sh` (used to actually trigger the build)  and `deploy-key.enc` (for accessing `freemint.github.io` to deploy the build for download) which are local to `mintlib`, other parts are downloaded.

For `2.` it's more interesting. For each branch there's a so called package on bintray (https://bintray.com/freemint/freemint). And each package is built in a slightly different way so we need different scripts to download. That's where `travis-scripts`'s branches come into play. 

For instance, the main package is freemint-master, available here: https://github.com/freemint/travis-scripts/tree/freemint-master producing output for https://bintray.com/freemint/freemint/snapshots.

Now, how it works together:

1. I want to change something in `freemint`s build scripts (say only for the main package)
1. I go to https://github.com/freemint/travis-scripts/tree/freemint-master/travis-freemint-master and choose appropriate file (you can see which file is invoked for what action in `freemint`'s .travis.yml: https://github.com/freemint/freemint/blob/master/.travis.yml) to edit
1. When done, `travis-scripts`'s `freemint-master` branch is "built" (packed in fact), and uploaded to https://bintray.com/freemint/travis-support/freemint#files
1. Then I go to `freemint`'s Travis console and restart the build (or wait for next commit to trigger it)

I know it looks really strange but the benefits are huge -- I can pack even a whole aranym image into the distribution archive and not to touch a single byte in `freemint` repository, all would be built and published transparently. 

If something unclear - do ask. :)

**Comment by mikrosk** [comment]
The second point about bintray is no longer true. There is nothing uploaded to nor downloaded from bintray. `freemint` just clones the respective branch from `travis-scripts` and use it what simplifies the whole process a lot. If you have further questions, feel free to reopen this. :)

**Comment by mfro0** [comment]
Thanks for the explanation, I guess I got it (hopefully ;) )
